# Generated by Django 5.1.4 on 2026-01-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('condition', models.CharField(choices=[('Bedridden', 'Bedridden'), ('Not Bedridden', 'Not Bedridden')], max_length=50)),
                ('disease', models.CharField(max_length=200)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('relative_name', models.CharField(blank=True, help_text='Relative staying with patient', max_length=200, null=True)),
            ],
        ),
    ]
