# Generated by Django 5.1.4 on 2026-01-01 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MaterialAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('allocation_date', models.DateField()),
                ('is_returnable', models.BooleanField(default=False)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_damaged', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('service_performed', models.TextField()),
                ('condition_assessment', models.CharField(choices=[('Active', 'Active'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='api.patient')),
            ],
        ),
    ]
