# Generated by Django 5.1.4 on 2026-01-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_patient_current_status_patient_is_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='notes_malayalam',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_english',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='symptoms_malayalam',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='time_spent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='condition_assessment',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='service_performed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
