# Generated by Django 5.1.4 on 2026-01-01 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialallocation',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.inventory'),
        ),
    ]
