# Generated by Django 5.1.4 on 2026-01-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_materialallocation_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialallocation',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='current_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Stable', 'Stable'), ('Moderate', 'Moderate'), ('Severe', 'Severe')], default='Active', max_length=50),
        ),
    ]
